#!/usr/bin/env bash
# -*- coding: utf-8 -*-

#######
### CONFIG
#######

user="root"
group=${user}
destPerm="600"
env="/usr/bin/env sudo -u ${user} "
dest="/backup"
filename="${dest}/$(date "+%Y-%m-%d_%H-%M-%S").tar.gz"
targets=(
    "/home"
    "/etc"
    "/srv"
    "/var/lib"
    "/var/log"
    "/var/db"
    "/var/spool"
    "/usr/local/bin"
)

#######
### EXECUTION
#######

${env} mkdir -pv ${dest}

${env} echo "Packing..."
${env} tar -zcvf ${filename} ${targets[*]}

${env} echo "Calculating checksum..."
${env} sha256sum ${filename} > ${filename}.sha256

${env} echo "Setting permissions..."
${env} chown ${user}:${group} -R ${dest}
${env} chmod ${destPerm} -R ${dest}
${env} echo -e "\n\n####\n"
${env} echo "Finished"
${env} echo "   Saved to: ${filename}"
${env} echo "   Permissions: ${user}:${group} ${destPerm}"
